development:
  github_app_id: <%= ENV['GITHUB_ID'] %>
  github_app_secret: <%= ENV['GITHUB_SECRET'] %>

production:
  github_app_id: <%= ENV['GITHUB_ID'] %>
  github_app_secret: <%= ENV['GITHUB_SECRET'] %>
  secret_key_bace: <%= ENV['SECRET_KEY_BACE'] %>